pipeline {
    agent any
    parameters {
        booleanParam(name: 'Dataplane', defaultValue: true, description: 'Dataplane image'),
        booleanParam(name: 'Controlplane', defaultValue: true, description: 'Controlplane image'),
        booleanParam(name: 'Generic', defaultValue: true, description: 'Generic image'),
    }
    environment {
        JOB_HOME    = "ansible-packer-ami"
       }
    stages {
        stage('Budiling AMI and sharing with PROD account.') {
            steps {
              sh '''#!/bin/bash -e
                cd ${JOB_HOME} || exit
                dp_image="dp"
                echo "$dp_image" 
#                if [ ${App} == 'Dataplane' ]
#                then
#                   echo "Dataplane: ${params.Dataplane}"
#
#                elif [ ${App} == 'generic' ]
#                then
#                   echo "Generic image"
#
#                elif [ ${App} == 'Controlplane' ]
#                then
#                   echo "Controlplane"
#                fi
                 '''
            }
        }
    }
}
