pipeline {
    agent any
    parameters {
        booleanParam(name: 'Dataplane', defaultValue: true, description: 'Dataplane image')
        booleanParam(name: 'Controlplane', defaultValue: true, description: 'Controlplane image')
        booleanParam(name: 'Generic', defaultValue: true, description: 'Generic image')
    }
    environment {
        JOB_HOME = "snapdir"
    }
    stages {
        stage('Building AMI and sharing with PROD account.') {
                  if (params.Dataplane) { 
                    echo "Dataplane image"
                     
		 } else (params.Controlplane) {
                      echo "conrol plane"
                 }
               
           }
        
    }
}
}
